using Tau.Ai;
using Tau.WebUi.Contracts;
using Tau.WebUi.Services;

namespace Tau.WebUi.Tests;

/// <summary>
/// Closes the Tau-native WebUi-local export/import row to verified-level local evidence: HTML and
/// Markdown exporter content + escaping + redaction, plus the importer error codes that the existing
/// <see cref="WebChatJsonlExporterTests"/> did not cover (empty line, missing type, invalid entry
/// type, missing required field). No external/browser dependency.
/// </summary>
public sealed class WebChatExportImportRoundTripTests
{
    private const string Secret = "sk-EXAMPLE_BASE_KEY_99999999";
    private const string GitHubSecret = "ghp_AAAA1111BBBB2222CCCC3333DDDD4444EEEE";

    [Fact]
    public void HtmlExporter_RendersHeaderMessagesToolsAttachmentsAndError()
    {
        var html = WebChatHtmlExporter.Render(CreateSession(), new TauSecretRedactor(enabled: false));

        Assert.StartsWith("<!doctype html>", html, StringComparison.Ordinal);
        Assert.EndsWith("</html>\n", html, StringComparison.Ordinal);
        Assert.Contains("<title>JSONL baseline — Tau WebUi</title>", html, StringComparison.Ordinal);
        Assert.Contains("<dt>Provider</dt><dd>openai</dd>", html, StringComparison.Ordinal);
        Assert.Contains("<dt>Model</dt><dd>gpt-5.4</dd>", html, StringComparison.Ordinal);
        Assert.Contains("class=\"message message--user\"", html, StringComparison.Ordinal);
        Assert.Contains("class=\"message message--assistant\"", html, StringComparison.Ordinal);
        Assert.Contains("<pre class=\"text\">inspect this</pre>", html, StringComparison.Ordinal);
        Assert.Contains("<details class=\"thinking\"><summary>thinking</summary><pre>reasoning</pre></details>", html, StringComparison.Ordinal);
        Assert.Contains("class=\"tool tool--completed\"", html, StringComparison.Ordinal);
        Assert.Contains("<summary>arguments</summary>", html, StringComparison.Ordinal);
        Assert.Contains("<summary>output</summary>", html, StringComparison.Ordinal);
        Assert.Contains("notes.txt", html, StringComparison.Ordinal);
        Assert.Contains("42 bytes", html, StringComparison.Ordinal);
        Assert.Contains("<p class=\"error\">boom</p>", html, StringComparison.Ordinal);
        Assert.Contains("Generated by Tau.WebUi</p>", html, StringComparison.Ordinal);
    }

    [Fact]
    public void HtmlExporter_EscapesMarkupAndRedactsSecrets()
    {
        var session = CreateSession() with
        {
            Title = $"<script>alert(1)</script> {Secret}",
            Messages =
            [
                new WebChatMessageDto("user", "1 < 2 && 3 > 2", DateTimeOffset.Parse("2026-05-23T01:03:00+00:00"))
            ]
        };

        var redacted = WebChatHtmlExporter.Render(session, new TauSecretRedactor(enabled: true));

        // Raw markup must be HTML-encoded, never emitted literally.
        Assert.DoesNotContain("<script>alert(1)</script>", redacted, StringComparison.Ordinal);
        Assert.Contains("&lt;script&gt;alert(1)&lt;/script&gt;", redacted, StringComparison.Ordinal);
        Assert.Contains("1 &lt; 2 &amp;&amp; 3 &gt; 2", redacted, StringComparison.Ordinal);
        Assert.DoesNotContain(Secret, redacted, StringComparison.Ordinal);
        Assert.Contains("secret redaction enabled", redacted, StringComparison.Ordinal);

        var plain = WebChatHtmlExporter.Render(session, new TauSecretRedactor(enabled: false));
        Assert.Contains(Secret, plain, StringComparison.Ordinal);
        Assert.DoesNotContain("secret redaction enabled", plain, StringComparison.Ordinal);
    }

    [Fact]
    public void MarkdownExporter_RendersHeadingsToolsAttachmentsAndError()
    {
        var markdown = WebChatMarkdownExporter.Render(CreateSession(), new TauSecretRedactor(enabled: false));

        Assert.StartsWith("# JSONL baseline", markdown, StringComparison.Ordinal);
        Assert.Contains("- Provider: `openai`", markdown, StringComparison.Ordinal);
        Assert.Contains("- Model: `gpt-5.4`", markdown, StringComparison.Ordinal);
        Assert.Contains("## User — ", markdown, StringComparison.Ordinal);
        Assert.Contains("## Assistant — ", markdown, StringComparison.Ordinal);
        Assert.Contains("<details><summary>thinking</summary>", markdown, StringComparison.Ordinal);
        Assert.Contains("inspect this", markdown, StringComparison.Ordinal);
        Assert.Contains("### Tool — `read` (completed)", markdown, StringComparison.Ordinal);
        Assert.Contains("Arguments:", markdown, StringComparison.Ordinal);
        Assert.Contains("Output:", markdown, StringComparison.Ordinal);
        Assert.Contains("Attachments:", markdown, StringComparison.Ordinal);
        Assert.Contains("- **notes.txt** (`text/plain`, 42 bytes)", markdown, StringComparison.Ordinal);
        Assert.Contains("> **Error:** boom", markdown, StringComparison.Ordinal);
        Assert.DoesNotContain("Secret redaction", markdown, StringComparison.Ordinal);
    }

    [Fact]
    public void MarkdownExporter_RedactsSecretsAndAnnouncesRedaction()
    {
        var session = CreateSession() with
        {
            Title = $"Session {Secret}",
            Messages =
            [
                new WebChatMessageDto("assistant", $"leak {GitHubSecret}", DateTimeOffset.Parse("2026-05-23T01:04:00+00:00"))
            ]
        };

        var redacted = WebChatMarkdownExporter.Render(session, new TauSecretRedactor(enabled: true));

        Assert.DoesNotContain(Secret, redacted, StringComparison.Ordinal);
        Assert.DoesNotContain(GitHubSecret, redacted, StringComparison.Ordinal);
        Assert.Contains("- Secret redaction: **on**", redacted, StringComparison.Ordinal);

        var plain = WebChatMarkdownExporter.Render(session, new TauSecretRedactor(enabled: false));
        Assert.Contains(Secret, plain, StringComparison.Ordinal);
        Assert.DoesNotContain("- Secret redaction: **on**", plain, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("missing_field")]
    public void Parse_RejectsHeaderMissingRequiredField(string expectedCode)
    {
        // Valid header shape but blank provider -> missing_field at the header line.
        var jsonl = "{\"type\":\"session\",\"version\":1,\"id\":\"session-1\",\"createdAt\":\"2026-05-23T01:02:03+00:00\",\"updatedAt\":\"2026-05-23T01:05:03+00:00\",\"title\":\"JSONL baseline\",\"provider\":\"\",\"model\":\"gpt-5.4\",\"source\":\"tau-webui\"}\n";

        var error = Assert.Throws<WebChatJsonlImportException>(() => WebChatJsonlImporter.Parse(jsonl));

        Assert.Equal(expectedCode, error.Code);
        Assert.Equal(1, error.LineNumber);
        Assert.Contains("session provider", error.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RejectsEmptyLineWithStableErrorCode()
    {
        var jsonl = ValidHeader() + "\n";

        var error = Assert.Throws<WebChatJsonlImportException>(() => WebChatJsonlImporter.Parse(jsonl));

        Assert.Equal("empty_line", error.Code);
        Assert.Equal(2, error.LineNumber);
    }

    [Fact]
    public void Parse_RejectsLineMissingTypeFieldWithStableErrorCode()
    {
        var jsonl = ValidHeader() + "{\"id\":\"message-000001\",\"role\":\"user\",\"text\":\"hi\"}\n";

        var error = Assert.Throws<WebChatJsonlImportException>(() => WebChatJsonlImporter.Parse(jsonl));

        Assert.Equal("missing_type", error.Code);
        Assert.Equal(2, error.LineNumber);
    }

    [Fact]
    public void Parse_RejectsNonMessageEntryTypeWithStableErrorCode()
    {
        var jsonl = ValidHeader() + "{\"type\":\"branch_summary\",\"id\":\"x\"}\n";

        var error = Assert.Throws<WebChatJsonlImportException>(() => WebChatJsonlImporter.Parse(jsonl));

        Assert.Equal("invalid_entry_type", error.Code);
        Assert.Equal(2, error.LineNumber);
    }

    [Fact]
    public void Parse_RejectsMessageMissingRoleWithStableErrorCode()
    {
        var jsonl = ValidHeader() +
            "{\"type\":\"message\",\"id\":\"message-000001\",\"parentId\":null,\"timestamp\":\"2026-05-23T01:03:00+00:00\",\"role\":\"\",\"text\":\"hi\"}\n";

        var error = Assert.Throws<WebChatJsonlImportException>(() => WebChatJsonlImporter.Parse(jsonl));

        Assert.Equal("missing_field", error.Code);
        Assert.Equal(2, error.LineNumber);
        Assert.Contains("message role", error.Message, StringComparison.Ordinal);
    }

    private static WebChatSessionDto CreateSession()
    {
        var createdAt = DateTimeOffset.Parse("2026-05-23T01:02:03+00:00");
        var updatedAt = DateTimeOffset.Parse("2026-05-23T01:05:03+00:00");
        var userAt = DateTimeOffset.Parse("2026-05-23T01:03:00+00:00");
        var assistantAt = DateTimeOffset.Parse("2026-05-23T01:04:00+00:00");
        var attachment = new WebChatAttachmentDto(
            "att-1",
            "document",
            "notes.txt",
            "text/plain",
            42,
            "aGVsbG8=",
            "hello");
        var toolCall = new WebChatToolCallDto(
            "tool-1",
            "read",
            "completed",
            "{\"path\":\"notes.txt\"}",
            "hello",
            CreatedAt: assistantAt);
        return new WebChatSessionDto(
            "session-1",
            "JSONL baseline",
            "openai",
            "gpt-5.4",
            createdAt,
            updatedAt,
            true,
            [
                new WebChatMessageDto("user", "inspect this", userAt, Attachments: [attachment]),
                new WebChatMessageDto(
                    "assistant",
                    "done",
                    assistantAt,
                    "reasoning",
                    ["start:read", "end:tool-1:ok"],
                    "boom",
                    ToolCalls: [toolCall])
            ]);
    }

    private static string ValidHeader() =>
        "{\"type\":\"session\",\"version\":1,\"id\":\"session-1\",\"createdAt\":\"2026-05-23T01:02:03+00:00\",\"updatedAt\":\"2026-05-23T01:05:03+00:00\",\"title\":\"JSONL baseline\",\"provider\":\"openai\",\"model\":\"gpt-5.4\",\"source\":\"tau-webui\"}\n";
}
