namespace Tau.Pods.Models;

public sealed record PodVllmServeOptions(
    string ModelId,
    string? DeploymentName = null,
    int Port = 8000,
    string? ServedModelName = null,
    IReadOnlyDictionary<string, string>? Environment = null,
    IReadOnlyList<string>? ExtraArgs = null,
    bool WaitForHealth = true,
    int HealthAttempts = 12,
    int HealthBackoffMilliseconds = 5000,
    string? ResolvedModelPath = null,
    string? Revision = null,
    bool Prefetch = false,
    int? RequestedGpuCount = null,
    string? Memory = null,
    string? Context = null);

public sealed record PodVllmServePlan(
    string DeploymentName,
    string ModelId,
    string ModelPath,
    int Port,
    string ServedModelName,
    string UnitName,
    string ServeCommand,
    string SystemdUnit,
    string MetadataJson,
    string RemoteCommand,
    bool UsesSnapshotDiscovery = false,
    string? Revision = null,
    string? KnownModelName = null,
    int? KnownModelGpuCount = null,
    IReadOnlyList<string>? KnownModelArgs = null,
    IReadOnlyDictionary<string, string>? KnownModelEnvironment = null,
    string? KnownModelNotes = null,
    int? RequestedGpuCount = null,
    IReadOnlyList<int>? SelectedGpuIds = null,
    string? MemoryOverride = null,
    double? MemoryUtilization = null,
    string? ContextOverride = null,
    int? ContextTokens = null,
    string LogPath = "");
