// <auto-generated />
// Generated by scripts/generate-tau-ai-models.ps1 from generated-models.seed.json.
using Tau.Ai.Providers;

namespace Tau.Ai.Registry;

public static class GeneratedBuiltInModels
{
    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, Model>> Catalog =
        new Dictionary<string, IReadOnlyDictionary<string, Model>>(StringComparer.OrdinalIgnoreCase)
        {
            ["azure-openai-responses"] = new Dictionary<string, Model>(StringComparer.OrdinalIgnoreCase)
            {
                ["gpt-4.1-mini"] = Create("gpt-4.1-mini", "GPT-4.1 mini", "azure-openai-responses", "azure-openai-responses", "", false, 1047576, 32768, 0.4m, 1.6m, 0.1m, 0.0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-4.1-nano"] = Create("gpt-4.1-nano", "GPT-4.1 nano", "azure-openai-responses", "azure-openai-responses", "", false, 1047576, 32768, 0.1m, 0.4m, 0.03m, 0.0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-4o"] = Create("gpt-4o", "GPT-4o", "azure-openai-responses", "azure-openai-responses", "", false, 128000, 16384, 2.5m, 10.0m, 1.25m, 0.0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5"] = Create("gpt-5", "GPT-5", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 1.25m, 10.0m, 0.125m, 0.0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5-mini"] = Create("gpt-5-mini", "GPT-5 Mini", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 0.25m, 2.0m, 0.025m, 0.0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-4"] = Create("gpt-4", "GPT-4", "azure-openai-responses", "azure-openai-responses", "", false, 8192, 8192, 30m, 60m, 0m, 0m) with
                {
                    InputModalities = ["text"]
                },
                ["gpt-4-turbo"] = Create("gpt-4-turbo", "GPT-4 Turbo", "azure-openai-responses", "azure-openai-responses", "", false, 128000, 4096, 10m, 30m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-4o-2024-05-13"] = Create("gpt-4o-2024-05-13", "GPT-4o (2024-05-13)", "azure-openai-responses", "azure-openai-responses", "", false, 128000, 4096, 5m, 15m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-4o-2024-08-06"] = Create("gpt-4o-2024-08-06", "GPT-4o (2024-08-06)", "azure-openai-responses", "azure-openai-responses", "", false, 128000, 16384, 2.5m, 10m, 1.25m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-4o-2024-11-20"] = Create("gpt-4o-2024-11-20", "GPT-4o (2024-11-20)", "azure-openai-responses", "azure-openai-responses", "", false, 128000, 16384, 2.5m, 10m, 1.25m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5-chat-latest"] = Create("gpt-5-chat-latest", "GPT-5 Chat Latest", "azure-openai-responses", "azure-openai-responses", "", false, 128000, 16384, 1.25m, 10m, 0.125m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5-codex"] = Create("gpt-5-codex", "GPT-5-Codex", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 1.25m, 10m, 0.125m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5-nano"] = Create("gpt-5-nano", "GPT-5 Nano", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 0.05m, 0.4m, 0.005m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5-pro"] = Create("gpt-5-pro", "GPT-5 Pro", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 272000, 15m, 120m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.1"] = Create("gpt-5.1", "GPT-5.1", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 1.25m, 10m, 0.13m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.1-chat-latest"] = Create("gpt-5.1-chat-latest", "GPT-5.1 Chat", "azure-openai-responses", "azure-openai-responses", "", true, 128000, 16384, 1.25m, 10m, 0.125m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.1-codex"] = Create("gpt-5.1-codex", "GPT-5.1 Codex", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 1.25m, 10m, 0.125m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.1-codex-max"] = Create("gpt-5.1-codex-max", "GPT-5.1 Codex Max", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 1.25m, 10m, 0.125m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.1-codex-mini"] = Create("gpt-5.1-codex-mini", "GPT-5.1 Codex mini", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 0.25m, 2m, 0.025m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.2-chat-latest"] = Create("gpt-5.2-chat-latest", "GPT-5.2 Chat", "azure-openai-responses", "azure-openai-responses", "", true, 128000, 16384, 1.75m, 14m, 0.175m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.2-codex"] = Create("gpt-5.2-codex", "GPT-5.2 Codex", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 1.75m, 14m, 0.175m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.2-pro"] = Create("gpt-5.2-pro", "GPT-5.2 Pro", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 21m, 168m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.3-chat-latest"] = Create("gpt-5.3-chat-latest", "GPT-5.3 Chat (latest)", "azure-openai-responses", "azure-openai-responses", "", false, 128000, 16384, 1.75m, 14m, 0.175m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.3-codex"] = Create("gpt-5.3-codex", "GPT-5.3 Codex", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 1.75m, 14m, 0.175m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.3-codex-spark"] = Create("gpt-5.3-codex-spark", "GPT-5.3 Codex Spark", "azure-openai-responses", "azure-openai-responses", "", true, 128000, 32000, 1.75m, 14m, 0.175m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.4"] = Create("gpt-5.4", "GPT-5.4", "azure-openai-responses", "azure-openai-responses", "", true, 272000, 128000, 2.5m, 15m, 0.25m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.4-mini"] = Create("gpt-5.4-mini", "GPT-5.4 mini", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 0.75m, 4.5m, 0.075m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.4-nano"] = Create("gpt-5.4-nano", "GPT-5.4 nano", "azure-openai-responses", "azure-openai-responses", "", true, 400000, 128000, 0.2m, 1.25m, 0.02m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.4-pro"] = Create("gpt-5.4-pro", "GPT-5.4 Pro", "azure-openai-responses", "azure-openai-responses", "", true, 1050000, 128000, 30m, 180m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["o1"] = Create("o1", "o1", "azure-openai-responses", "azure-openai-responses", "", true, 200000, 100000, 15m, 60m, 7.5m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["o1-pro"] = Create("o1-pro", "o1-pro", "azure-openai-responses", "azure-openai-responses", "", true, 200000, 100000, 150m, 600m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["o3"] = Create("o3", "o3", "azure-openai-responses", "azure-openai-responses", "", true, 200000, 100000, 2m, 8m, 0.5m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["o3-deep-research"] = Create("o3-deep-research", "o3-deep-research", "azure-openai-responses", "azure-openai-responses", "", true, 200000, 100000, 10m, 40m, 2.5m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["o3-mini"] = Create("o3-mini", "o3-mini", "azure-openai-responses", "azure-openai-responses", "", true, 200000, 100000, 1.1m, 4.4m, 0.55m, 0m) with
                {
                    InputModalities = ["text"]
                },
                ["o3-pro"] = Create("o3-pro", "o3-pro", "azure-openai-responses", "azure-openai-responses", "", true, 200000, 100000, 20m, 80m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["o4-mini"] = Create("o4-mini", "o4-mini", "azure-openai-responses", "azure-openai-responses", "", true, 200000, 100000, 1.1m, 4.4m, 0.28m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["o4-mini-deep-research"] = Create("o4-mini-deep-research", "o4-mini-deep-research", "azure-openai-responses", "azure-openai-responses", "", true, 200000, 100000, 2m, 8m, 0.5m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
            },
            ["openai-codex"] = new Dictionary<string, Model>(StringComparer.OrdinalIgnoreCase)
            {
                ["gpt-5.1"] = Create("gpt-5.1", "GPT-5.1", "openai-codex-responses", "openai-codex", "https://chatgpt.com/backend-api", true, 272000, 128000, 1.25m, 10.0m, 0.125m, 0.0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.3-codex"] = Create("gpt-5.3-codex", "GPT-5.3 Codex", "openai-codex-responses", "openai-codex", "https://chatgpt.com/backend-api", true, 272000, 128000, 1.75m, 14.0m, 0.175m, 0.0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.1-codex-max"] = Create("gpt-5.1-codex-max", "GPT-5.1 Codex Max", "openai-codex-responses", "openai-codex", "https://chatgpt.com/backend-api", true, 272000, 128000, 1.25m, 10m, 0.125m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.1-codex-mini"] = Create("gpt-5.1-codex-mini", "GPT-5.1 Codex Mini", "openai-codex-responses", "openai-codex", "https://chatgpt.com/backend-api", true, 272000, 128000, 0.25m, 2m, 0.025m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.2"] = Create("gpt-5.2", "GPT-5.2", "openai-codex-responses", "openai-codex", "https://chatgpt.com/backend-api", true, 272000, 128000, 1.75m, 14m, 0.175m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-5.3-codex-spark"] = Create("gpt-5.3-codex-spark", "GPT-5.3 Codex Spark", "openai-codex-responses", "openai-codex", "https://chatgpt.com/backend-api", true, 128000, 128000, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text"]
                },
                ["gpt-5.4-mini"] = Create("gpt-5.4-mini", "GPT-5.4 Mini", "openai-codex-responses", "openai-codex", "https://chatgpt.com/backend-api", true, 272000, 128000, 0.75m, 4.5m, 0.075m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
            },
            ["github-copilot"] = new Dictionary<string, Model>(StringComparer.OrdinalIgnoreCase)
            {
                ["gpt-5-mini"] = Create("gpt-5-mini", "GPT-5-mini", "openai-responses", "github-copilot", "https://api.individual.githubcopilot.com", true, 264000, 64000, 0.0m, 0.0m, 0.0m, 0.0m) with
                {
                    InputModalities = ["text", "image"],
                    Headers = GitHubCopilotHeaders.CreateStaticHeaders()
                },
                ["gpt-5.1-codex"] = Create("gpt-5.1-codex", "GPT-5.1-Codex", "openai-responses", "github-copilot", "https://api.individual.githubcopilot.com", true, 400000, 128000, 0.0m, 0.0m, 0.0m, 0.0m) with
                {
                    InputModalities = ["text", "image"],
                    Headers = GitHubCopilotHeaders.CreateStaticHeaders()
                },
                ["gpt-5"] = Create("gpt-5", "GPT-5", "openai-responses", "github-copilot", "https://api.individual.githubcopilot.com", true, 128000, 128000, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    Headers = GitHubCopilotHeaders.CreateStaticHeaders()
                },
                ["gpt-5.1"] = Create("gpt-5.1", "GPT-5.1", "openai-responses", "github-copilot", "https://api.individual.githubcopilot.com", true, 264000, 64000, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    Headers = GitHubCopilotHeaders.CreateStaticHeaders()
                },
                ["gpt-5.1-codex-max"] = Create("gpt-5.1-codex-max", "GPT-5.1-Codex-max", "openai-responses", "github-copilot", "https://api.individual.githubcopilot.com", true, 400000, 128000, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    Headers = GitHubCopilotHeaders.CreateStaticHeaders()
                },
                ["gpt-5.1-codex-mini"] = Create("gpt-5.1-codex-mini", "GPT-5.1-Codex-mini", "openai-responses", "github-copilot", "https://api.individual.githubcopilot.com", true, 400000, 128000, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    Headers = GitHubCopilotHeaders.CreateStaticHeaders()
                },
                ["gpt-5.2"] = Create("gpt-5.2", "GPT-5.2", "openai-responses", "github-copilot", "https://api.individual.githubcopilot.com", true, 264000, 64000, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    Headers = GitHubCopilotHeaders.CreateStaticHeaders()
                },
                ["gpt-5.2-codex"] = Create("gpt-5.2-codex", "GPT-5.2-Codex", "openai-responses", "github-copilot", "https://api.individual.githubcopilot.com", true, 400000, 128000, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    Headers = GitHubCopilotHeaders.CreateStaticHeaders()
                },
                ["gpt-5.4"] = Create("gpt-5.4", "GPT-5.4", "openai-responses", "github-copilot", "https://api.individual.githubcopilot.com", true, 400000, 128000, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    Headers = GitHubCopilotHeaders.CreateStaticHeaders()
                },
                ["gpt-5.4-mini"] = Create("gpt-5.4-mini", "GPT-5.4 Mini", "openai-responses", "github-copilot", "https://api.individual.githubcopilot.com", true, 400000, 128000, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    Headers = GitHubCopilotHeaders.CreateStaticHeaders()
                },
            },
            ["google-gemini-cli"] = new Dictionary<string, Model>(StringComparer.OrdinalIgnoreCase)
            {
                ["gemini-2.0-flash"] = Create("gemini-2.0-flash", "Gemini 2.0 Flash (Cloud Code Assist)", "google-gemini-cli", "google-gemini-cli", "https://cloudcode-pa.googleapis.com", false, 1048576, 8192, 0.0m, 0.0m, 0.0m, 0.0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gemini-3-flash-preview"] = Create("gemini-3-flash-preview", "Gemini 3 Flash Preview (Cloud Code Assist)", "google-gemini-cli", "google-gemini-cli", "https://cloudcode-pa.googleapis.com", true, 1048576, 65535, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gemini-3-pro-preview"] = Create("gemini-3-pro-preview", "Gemini 3 Pro Preview (Cloud Code Assist)", "google-gemini-cli", "google-gemini-cli", "https://cloudcode-pa.googleapis.com", true, 1048576, 65535, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gemini-3.1-pro-preview"] = Create("gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview (Cloud Code Assist)", "google-gemini-cli", "google-gemini-cli", "https://cloudcode-pa.googleapis.com", true, 1048576, 65535, 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"]
                },
            },
            ["google-antigravity"] = new Dictionary<string, Model>(StringComparer.OrdinalIgnoreCase)
            {
                ["gemini-3-flash"] = Create("gemini-3-flash", "Gemini 3 Flash (Antigravity)", "google-gemini-cli", "google-antigravity", "", true, 1048576, 65535, 0.5m, 3.0m, 0.5m, 0.0m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["claude-sonnet-4-5-thinking"] = Create("claude-sonnet-4-5-thinking", "Claude Sonnet 4.5 Thinking (Antigravity)", "google-gemini-cli", "google-antigravity", "", true, 200000, 64000, 3.0m, 15.0m, 0.3m, 3.75m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gpt-oss-120b-medium"] = Create("gpt-oss-120b-medium", "GPT-OSS 120B Medium (Antigravity)", "google-gemini-cli", "google-antigravity", "", false, 131072, 32768, 0.09m, 0.36m, 0.0m, 0.0m) with
                {
                    InputModalities = ["text"]
                },
                ["claude-opus-4-5-thinking"] = Create("claude-opus-4-5-thinking", "Claude Opus 4.5 Thinking (Antigravity)", "google-gemini-cli", "google-antigravity", "", true, 200000, 64000, 5m, 25m, 0.5m, 6.25m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["claude-opus-4-6-thinking"] = Create("claude-opus-4-6-thinking", "Claude Opus 4.6 Thinking (Antigravity)", "google-gemini-cli", "google-antigravity", "", true, 200000, 128000, 5m, 25m, 0.5m, 6.25m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["claude-sonnet-4-5"] = Create("claude-sonnet-4-5", "Claude Sonnet 4.5 (Antigravity)", "google-gemini-cli", "google-antigravity", "", false, 200000, 64000, 3m, 15m, 0.3m, 3.75m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["claude-sonnet-4-6"] = Create("claude-sonnet-4-6", "Claude Sonnet 4.6 (Antigravity)", "google-gemini-cli", "google-antigravity", "", true, 200000, 64000, 3m, 15m, 0.3m, 3.75m) with
                {
                    InputModalities = ["text", "image"]
                },
                ["gemini-3.1-pro-low"] = Create("gemini-3.1-pro-low", "Gemini 3.1 Pro Low (Antigravity)", "google-gemini-cli", "google-antigravity", "", true, 1048576, 65535, 2m, 12m, 0.2m, 2.375m) with
                {
                    InputModalities = ["text", "image"]
                },
            },
        };

    private static Model Create(
        string id,
        string name,
        string api,
        string provider,
        string baseUrl,
        bool reasoning,
        int contextWindow,
        int maxOutputTokens,
        decimal inputCost,
        decimal outputCost,
        decimal cacheReadCost,
        decimal cacheWriteCost) =>
        new()
        {
            Id = id,
            Name = name,
            Api = api,
            Provider = provider,
            BaseUrl = string.IsNullOrWhiteSpace(baseUrl) ? string.Empty : baseUrl,
            Reasoning = reasoning,
            ContextWindow = contextWindow,
            MaxOutputTokens = maxOutputTokens,
            Cost = new ModelCost(inputCost, outputCost, cacheReadCost, cacheWriteCost)
        };
}
