// <auto-generated />
// Generated from C:\Users\zhouh\Desktop\pi-main\packages\ai\src\image-models.generated.ts.
namespace Tau.Ai.Registry;

public static class GeneratedBuiltInImageModels
{
    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, ImagesModel>> Catalog =
        new Dictionary<string, IReadOnlyDictionary<string, ImagesModel>>(StringComparer.OrdinalIgnoreCase)
        {
            ["openrouter"] = new Dictionary<string, ImagesModel>(StringComparer.OrdinalIgnoreCase)
            {
                ["black-forest-labs/flux.2-flex"] = Create("black-forest-labs/flux.2-flex", "Black Forest Labs: FLUX.2 Flex", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["black-forest-labs/flux.2-klein-4b"] = Create("black-forest-labs/flux.2-klein-4b", "Black Forest Labs: FLUX.2 Klein 4B", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["black-forest-labs/flux.2-max"] = Create("black-forest-labs/flux.2-max", "Black Forest Labs: FLUX.2 Max", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["black-forest-labs/flux.2-pro"] = Create("black-forest-labs/flux.2-pro", "Black Forest Labs: FLUX.2 Pro", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["bytedance-seed/seedream-4.5"] = Create("bytedance-seed/seedream-4.5", "ByteDance Seed: Seedream 4.5", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["image", "text"],
                    OutputModalities = ["image"]
                },
                ["google/gemini-2.5-flash-image"] = Create("google/gemini-2.5-flash-image", "Google: Nano Banana (Gemini 2.5 Flash Image)", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0.3m, 2.5m, 0.03m, 0.08333333333333334m) with
                {
                    InputModalities = ["image", "text"],
                    OutputModalities = ["image", "text"]
                },
                ["google/gemini-3-pro-image"] = Create("google/gemini-3-pro-image", "Google: Nano Banana Pro (Gemini 3 Pro Image)", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 2m, 12m, 0.19999999999999998m, 0.375m) with
                {
                    InputModalities = ["image", "text"],
                    OutputModalities = ["image", "text"]
                },
                ["google/gemini-3-pro-image-preview"] = Create("google/gemini-3-pro-image-preview", "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 2m, 12m, 0.19999999999999998m, 0.375m) with
                {
                    InputModalities = ["image", "text"],
                    OutputModalities = ["image", "text"]
                },
                ["google/gemini-3.1-flash-image"] = Create("google/gemini-3.1-flash-image", "Google: Nano Banana 2 (Gemini 3.1 Flash Image)", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0.5m, 3m, 0m, 0m) with
                {
                    InputModalities = ["image", "text"],
                    OutputModalities = ["image", "text"]
                },
                ["google/gemini-3.1-flash-image-preview"] = Create("google/gemini-3.1-flash-image-preview", "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0.5m, 3m, 0m, 0m) with
                {
                    InputModalities = ["image", "text"],
                    OutputModalities = ["image", "text"]
                },
                ["microsoft/mai-image-2.5"] = Create("microsoft/mai-image-2.5", "Microsoft: MAI-Image-2.5", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 5m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["openai/gpt-5-image"] = Create("openai/gpt-5-image", "OpenAI: GPT-5 Image", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 10m, 10m, 1.25m, 0m) with
                {
                    InputModalities = ["image", "text"],
                    OutputModalities = ["image", "text"]
                },
                ["openai/gpt-5-image-mini"] = Create("openai/gpt-5-image-mini", "OpenAI: GPT-5 Image Mini", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 2.5m, 2m, 0.25m, 0m) with
                {
                    InputModalities = ["image", "text"],
                    OutputModalities = ["image", "text"]
                },
                ["openai/gpt-5.4-image-2"] = Create("openai/gpt-5.4-image-2", "OpenAI: GPT-5.4 Image 2", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 8m, 15m, 2m, 0m) with
                {
                    InputModalities = ["image", "text"],
                    OutputModalities = ["image", "text"]
                },
                ["openrouter/auto"] = Create("openrouter/auto", "Auto Router", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", -1000000m, -1000000m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["text", "image"]
                },
                ["recraft/recraft-v3"] = Create("recraft/recraft-v3", "Recraft: Recraft V3", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["recraft/recraft-v4"] = Create("recraft/recraft-v4", "Recraft: Recraft V4", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["recraft/recraft-v4-pro"] = Create("recraft/recraft-v4-pro", "Recraft: Recraft V4 Pro", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["recraft/recraft-v4-pro-vector"] = Create("recraft/recraft-v4-pro-vector", "Recraft: Recraft V4 Pro Vector", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["recraft/recraft-v4-vector"] = Create("recraft/recraft-v4-vector", "Recraft: Recraft V4 Vector", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["recraft/recraft-v4.1"] = Create("recraft/recraft-v4.1", "Recraft: Recraft V4.1", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["recraft/recraft-v4.1-pro"] = Create("recraft/recraft-v4.1-pro", "Recraft: Recraft V4.1 Pro", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["recraft/recraft-v4.1-pro-vector"] = Create("recraft/recraft-v4.1-pro-vector", "Recraft: Recraft V4.1 Pro Vector", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["recraft/recraft-v4.1-utility"] = Create("recraft/recraft-v4.1-utility", "Recraft: Recraft V4.1 Utility", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["recraft/recraft-v4.1-utility-pro"] = Create("recraft/recraft-v4.1-utility-pro", "Recraft: Recraft V4.1 Utility Pro", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["recraft/recraft-v4.1-vector"] = Create("recraft/recraft-v4.1-vector", "Recraft: Recraft V4.1 Vector", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["sourceful/riverflow-v2-fast"] = Create("sourceful/riverflow-v2-fast", "Sourceful: Riverflow V2 Fast", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["sourceful/riverflow-v2-fast-preview"] = Create("sourceful/riverflow-v2-fast-preview", "Sourceful: Riverflow V2 Fast Preview", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["sourceful/riverflow-v2-max-preview"] = Create("sourceful/riverflow-v2-max-preview", "Sourceful: Riverflow V2 Max Preview", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["sourceful/riverflow-v2-pro"] = Create("sourceful/riverflow-v2-pro", "Sourceful: Riverflow V2 Pro", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["sourceful/riverflow-v2-standard-preview"] = Create("sourceful/riverflow-v2-standard-preview", "Sourceful: Riverflow V2 Standard Preview", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["sourceful/riverflow-v2.5-fast"] = Create("sourceful/riverflow-v2.5-fast", "Sourceful: Riverflow V2.5 Fast", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["sourceful/riverflow-v2.5-pro"] = Create("sourceful/riverflow-v2.5-pro", "Sourceful: Riverflow V2.5 Pro", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
                ["x-ai/grok-imagine-image-quality"] = Create("x-ai/grok-imagine-image-quality", "xAI: Grok Imagine Image Quality", "openrouter-images", "openrouter", "https://openrouter.ai/api/v1", 0m, 0m, 0m, 0m) with
                {
                    InputModalities = ["text", "image"],
                    OutputModalities = ["image"]
                },
            }
        };

    private static ImagesModel Create(
        string id,
        string name,
        string api,
        string provider,
        string baseUrl,
        decimal inputCost,
        decimal outputCost,
        decimal cacheReadCost,
        decimal cacheWriteCost) =>
        new()
        {
            Id = id,
            Name = name,
            Api = api,
            Provider = provider,
            BaseUrl = baseUrl,
            Reasoning = false,
            Cost = new ModelCost(inputCost, outputCost, cacheReadCost, cacheWriteCost)
        };
}
