// <auto-generated />
// Loaded from generated-models.seed.json.
#nullable enable
using System.Reflection;
using System.Text.Json;
using Tau.Ai.Providers;

namespace Tau.Ai.Registry;

public static class GeneratedBuiltInModels
{
    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, Model>> Catalog = LoadCatalog();

    private static IReadOnlyDictionary<string, IReadOnlyDictionary<string, Model>> LoadCatalog()
    {
        var assembly = typeof(GeneratedBuiltInModels).Assembly;
        var resourceName = assembly
            .GetManifestResourceNames()
            .Single(name => name.EndsWith(".generated-models.seed.json", StringComparison.Ordinal));

        using var stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded model seed resource '{resourceName}' was not found.");
        using var document = JsonDocument.Parse(stream);

        if (!document.RootElement.TryGetProperty("providers", out var providers) ||
            providers.ValueKind != JsonValueKind.Object)
        {
            return new Dictionary<string, IReadOnlyDictionary<string, Model>>(StringComparer.OrdinalIgnoreCase);
        }

        var catalog = new Dictionary<string, IReadOnlyDictionary<string, Model>>(StringComparer.OrdinalIgnoreCase);
        foreach (var providerProperty in providers.EnumerateObject())
        {
            if (providerProperty.Value.ValueKind != JsonValueKind.Array)
            {
                continue;
            }

            var models = new Dictionary<string, Model>(StringComparer.OrdinalIgnoreCase);
            foreach (var modelElement in providerProperty.Value.EnumerateArray())
            {
                if (!TryReadModel(providerProperty.Name, modelElement, out var model))
                {
                    continue;
                }

                models[model.Id] = model;
            }

            if (models.Count > 0)
            {
                catalog[providerProperty.Name] = models;
            }
        }

        return catalog;
    }

    private static bool TryReadModel(string providerName, JsonElement element, out Model model)
    {
        model = default!;
        var id = GetString(element, "id");
        if (string.IsNullOrWhiteSpace(id))
        {
            return false;
        }

        var provider = GetString(element, "provider") ?? providerName;
        model = new Model
        {
            Id = id,
            Name = GetString(element, "name") ?? id,
            Api = ModelApiNames.Normalize(GetString(element, "api")) ?? ModelApiNames.OpenAiChatCompletions,
            Provider = provider,
            BaseUrl = GetString(element, "baseUrl") ?? string.Empty,
            Reasoning = GetBool(element, "reasoning") ?? false,
            InputModalities = ParseStringArray(element, "inputModalities") ?? ParseStringArray(element, "input") ?? ["text"],
            Cost = ParseCost(element),
            ContextWindow = GetInt(element, "contextWindow"),
            MaxOutputTokens = GetInt(element, "maxOutputTokens") ?? GetInt(element, "maxTokens"),
            Headers = provider.Equals("github-copilot", StringComparison.OrdinalIgnoreCase)
                ? GitHubCopilotHeaders.CreateStaticHeaders()
                : null,
            Compat = ParseCompat(element)
        };
        return true;
    }

    private static ModelCost ParseCost(JsonElement element)
    {
        if (!element.TryGetProperty("cost", out var cost) || cost.ValueKind != JsonValueKind.Object)
        {
            return new ModelCost(0m, 0m, 0m, 0m);
        }

        return new ModelCost(
            GetDecimal(cost, "input") ?? 0m,
            GetDecimal(cost, "output") ?? 0m,
            GetDecimal(cost, "cacheRead") ?? 0m,
            GetDecimal(cost, "cacheWrite") ?? 0m);
    }

    private static ModelCompatibility? ParseCompat(JsonElement element)
    {
        if (!element.TryGetProperty("compat", out var compat) || compat.ValueKind != JsonValueKind.Object)
        {
            return ParseReasoningEffortMap(element) is { } map
                ? new ModelCompatibility { ReasoningEffortMap = map }
                : null;
        }

        var parsed = new ModelCompatibility
        {
            SupportsStore = GetBool(compat, "supportsStore"),
            SupportsDeveloperRole = GetBool(compat, "supportsDeveloperRole"),
            SupportsReasoningEffort = GetBool(compat, "supportsReasoningEffort"),
            ReasoningEffortMap = ParseReasoningEffortMap(element),
            SupportsUsageInStreaming = GetBool(compat, "supportsUsageInStreaming"),
            MaxTokensField = GetString(compat, "maxTokensField"),
            RequiresToolResultName = GetBool(compat, "requiresToolResultName"),
            RequiresAssistantAfterToolResult = GetBool(compat, "requiresAssistantAfterToolResult"),
            RequiresThinkingAsText = GetBool(compat, "requiresThinkingAsText"),
            RequiresReasoningContentOnAssistantMessages = GetBool(compat, "requiresReasoningContentOnAssistantMessages"),
            ThinkingFormat = GetString(compat, "thinkingFormat"),
            OpenRouterRouting = ParseObjectDictionary(compat, "openRouterRouting"),
            VercelGatewayRouting = ParseVercelGatewayRouting(compat, "vercelGatewayRouting"),
            ZaiToolStream = GetBool(compat, "zaiToolStream"),
            SupportsStrictMode = GetBool(compat, "supportsStrictMode"),
            CacheControlFormat = GetString(compat, "cacheControlFormat"),
            SendSessionAffinityHeaders = GetBool(compat, "sendSessionAffinityHeaders"),
            SupportsLongCacheRetention = GetBool(compat, "supportsLongCacheRetention"),
            SupportsTemperature = GetBool(compat, "supportsTemperature"),
            ForceAdaptiveThinking = GetBool(compat, "forceAdaptiveThinking"),
            SupportsEagerToolInputStreaming = GetBool(compat, "supportsEagerToolInputStreaming"),
            SupportsCacheControlOnTools = GetBool(compat, "supportsCacheControlOnTools"),
            AllowEmptySignature = GetBool(compat, "allowEmptySignature")
        };

        return parsed;
    }

    private static IReadOnlyDictionary<string, string>? ParseReasoningEffortMap(JsonElement element) =>
        ParseStringDictionary(element, "reasoningEffortMap") ?? ParseStringDictionary(element, "thinkingLevelMap");

    private static VercelGatewayRouting? ParseVercelGatewayRouting(JsonElement element, string propertyName)
    {
        if (!element.TryGetProperty(propertyName, out var value) || value.ValueKind != JsonValueKind.Object)
        {
            return null;
        }

        return new VercelGatewayRouting
        {
            Only = ParseStringArray(value, "only"),
            Order = ParseStringArray(value, "order")
        };
    }

    private static Dictionary<string, string>? ParseStringDictionary(JsonElement element, string propertyName)
    {
        if (!element.TryGetProperty(propertyName, out var value) || value.ValueKind != JsonValueKind.Object)
        {
            return null;
        }

        var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var property in value.EnumerateObject())
        {
            if (property.Value.ValueKind == JsonValueKind.String)
            {
                result[property.Name] = property.Value.GetString() ?? string.Empty;
            }
        }

        return result.Count == 0 ? null : result;
    }

    private static IDictionary<string, object>? ParseObjectDictionary(JsonElement element, string propertyName)
    {
        if (!element.TryGetProperty(propertyName, out var value) || value.ValueKind != JsonValueKind.Object)
        {
            return null;
        }

        var result = new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase);
        foreach (var property in value.EnumerateObject())
        {
            result[property.Name] = ConvertJsonValue(property.Value);
        }

        return result.Count == 0 ? null : result;
    }

    private static object ConvertJsonValue(JsonElement value) =>
        value.ValueKind switch
        {
            JsonValueKind.String => value.GetString() ?? string.Empty,
            JsonValueKind.Number => value.TryGetInt64(out var integer) ? integer : value.GetDecimal(),
            JsonValueKind.True => true,
            JsonValueKind.False => false,
            JsonValueKind.Array => value.EnumerateArray().Select(ConvertJsonValue).ToArray(),
            JsonValueKind.Object => value.EnumerateObject().ToDictionary(
                property => property.Name,
                property => ConvertJsonValue(property.Value),
                StringComparer.OrdinalIgnoreCase),
            _ => string.Empty
        };

    private static IReadOnlyList<string>? ParseStringArray(JsonElement element, string propertyName)
    {
        if (!element.TryGetProperty(propertyName, out var value) || value.ValueKind != JsonValueKind.Array)
        {
            return null;
        }

        var result = value
            .EnumerateArray()
            .Where(item => item.ValueKind == JsonValueKind.String)
            .Select(item => item.GetString())
            .Where(item => !string.IsNullOrWhiteSpace(item))
            .Select(item => item!)
            .ToArray();
        return result.Length == 0 ? null : result;
    }

    private static string? GetString(JsonElement element, string propertyName) =>
        element.TryGetProperty(propertyName, out var property) && property.ValueKind == JsonValueKind.String
            ? property.GetString()
            : null;

    private static bool? GetBool(JsonElement element, string propertyName) =>
        element.TryGetProperty(propertyName, out var property) &&
        (property.ValueKind == JsonValueKind.True || property.ValueKind == JsonValueKind.False)
            ? property.GetBoolean()
            : null;

    private static int? GetInt(JsonElement element, string propertyName) =>
        element.TryGetProperty(propertyName, out var property) && property.ValueKind == JsonValueKind.Number
            ? property.GetInt32()
            : null;

    private static decimal? GetDecimal(JsonElement element, string propertyName) =>
        element.TryGetProperty(propertyName, out var property) && property.ValueKind == JsonValueKind.Number
            ? property.GetDecimal()
            : null;
}
