using System.Net;
using System.Text;
using Tau.Ai;
using Tau.WebUi.Contracts;

namespace Tau.WebUi.Services;

public static class WebChatHtmlExporter
{
    public static string Render(WebChatSessionDto session, TauSecretRedactor redactor)
    {
        if (session is null)
        {
            throw new ArgumentNullException(nameof(session));
        }

        var sb = new StringBuilder(8 * 1024);
        sb.Append("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n");
        sb.Append("<title>");
        sb.Append(Html(redactor.Redact(session.Title)));
        sb.Append(" — Tau WebUi</title>\n");
        sb.Append("<style>\n");
        sb.Append(Css);
        sb.Append("</style>\n</head>\n<body>\n");
        sb.Append("<header><h1>");
        sb.Append(Html(redactor.Redact(session.Title)));
        sb.Append("</h1><dl class=\"meta\"><dt>Provider</dt><dd>");
        sb.Append(Html(session.Provider));
        sb.Append("</dd><dt>Model</dt><dd>");
        sb.Append(Html(session.Model));
        sb.Append("</dd><dt>Created</dt><dd>");
        sb.Append(Html(session.CreatedAt.ToString("O")));
        sb.Append("</dd><dt>Updated</dt><dd>");
        sb.Append(Html(session.UpdatedAt.ToString("O")));
        sb.Append("</dd></dl></header>\n<main>\n");

        foreach (var message in session.Messages)
        {
            RenderMessage(sb, message, redactor);
        }

        sb.Append("</main>\n");
        sb.Append("<footer><p>Generated by Tau.WebUi");
        if (redactor.Enabled)
        {
            sb.Append(" · secret redaction enabled");
        }
        sb.Append("</p></footer>\n</body>\n</html>\n");
        return sb.ToString();
    }

    private static void RenderMessage(StringBuilder sb, WebChatMessageDto message, TauSecretRedactor redactor)
    {
        var role = string.IsNullOrEmpty(message.Role) ? "message" : message.Role;
        sb.Append("<article class=\"message message--");
        sb.Append(Html(role));
        sb.Append("\">\n<header class=\"message__meta\"><span class=\"role\">");
        sb.Append(Html(role));
        sb.Append("</span><time>");
        sb.Append(Html(message.Timestamp.ToString("O")));
        sb.Append("</time></header>\n");

        if (!string.IsNullOrEmpty(message.Thinking))
        {
            sb.Append("<details class=\"thinking\"><summary>thinking</summary><pre>");
            sb.Append(Html(redactor.Redact(message.Thinking)));
            sb.Append("</pre></details>\n");
        }

        if (!string.IsNullOrEmpty(message.Text))
        {
            sb.Append("<pre class=\"text\">");
            sb.Append(Html(redactor.Redact(message.Text)));
            sb.Append("</pre>\n");
        }

        if (message.ToolCalls is { Count: > 0 })
        {
            sb.Append("<ul class=\"tools\">\n");
            foreach (var tool in message.ToolCalls)
            {
                RenderToolCall(sb, tool, redactor);
            }
            sb.Append("</ul>\n");
        }

        if (message.Attachments is { Count: > 0 })
        {
            sb.Append("<ul class=\"attachments\">\n");
            foreach (var attachment in message.Attachments)
            {
                sb.Append("<li><span class=\"attachment-name\">");
                sb.Append(Html(redactor.Redact(attachment.FileName)));
                sb.Append("</span> <span class=\"attachment-meta\">(");
                sb.Append(Html(attachment.MimeType));
                sb.Append(", ");
                sb.Append(attachment.Size.ToString(System.Globalization.CultureInfo.InvariantCulture));
                sb.Append(" bytes)</span>");
                if (!string.IsNullOrEmpty(attachment.ExtractedText))
                {
                    sb.Append("<details><summary>extracted text</summary><pre>");
                    sb.Append(Html(redactor.Redact(attachment.ExtractedText)));
                    sb.Append("</pre></details>");
                }
                sb.Append("</li>\n");
            }
            sb.Append("</ul>\n");
        }

        if (!string.IsNullOrEmpty(message.Error))
        {
            sb.Append("<p class=\"error\">");
            sb.Append(Html(redactor.Redact(message.Error)));
            sb.Append("</p>\n");
        }

        sb.Append("</article>\n");
    }

    private static void RenderToolCall(StringBuilder sb, WebChatToolCallDto tool, TauSecretRedactor redactor)
    {
        sb.Append("<li class=\"tool tool--");
        sb.Append(Html(tool.Status));
        sb.Append("\"><div class=\"tool__name\">");
        sb.Append(Html(tool.ToolName));
        sb.Append(" <span class=\"tool__status\">");
        sb.Append(Html(tool.Status));
        sb.Append("</span></div>");

        if (!string.IsNullOrEmpty(tool.Arguments))
        {
            sb.Append("<details><summary>arguments</summary><pre>");
            sb.Append(Html(redactor.Redact(tool.Arguments)));
            sb.Append("</pre></details>");
        }

        if (!string.IsNullOrEmpty(tool.Output))
        {
            sb.Append("<details><summary>output</summary><pre>");
            sb.Append(Html(redactor.Redact(tool.Output)));
            sb.Append("</pre></details>");
        }

        sb.Append("</li>\n");
    }

    private static string Html(string? value) => WebUtility.HtmlEncode(value ?? string.Empty);

    private const string Css = """
        body { font-family: -apple-system, Segoe UI, system-ui, sans-serif; margin: 0; padding: 1.5rem; background: #fafafa; color: #1f2933; }
        header { margin-bottom: 1.5rem; border-bottom: 1px solid #e0e3e6; padding-bottom: 1rem; }
        header h1 { margin: 0 0 0.5rem 0; }
        dl.meta { display: grid; grid-template-columns: auto 1fr; gap: 0.25rem 1rem; margin: 0; }
        dl.meta dt { font-weight: 600; color: #52606d; }
        dl.meta dd { margin: 0; font-family: ui-monospace, SFMono-Regular, monospace; font-size: 0.85rem; }
        .message { background: #ffffff; border: 1px solid #e0e3e6; border-radius: 6px; padding: 0.75rem 1rem; margin: 0 0 0.75rem 0; }
        .message--user { background: #f5fbff; }
        .message--assistant { background: #f7fff5; }
        .message__meta { display: flex; gap: 1rem; font-size: 0.75rem; color: #52606d; margin-bottom: 0.5rem; }
        .role { font-weight: 600; text-transform: uppercase; }
        pre.text, pre { white-space: pre-wrap; word-wrap: break-word; margin: 0.25rem 0; font-family: ui-monospace, SFMono-Regular, monospace; font-size: 0.9rem; }
        details.thinking { font-size: 0.85rem; color: #52606d; }
        ul.tools, ul.attachments { list-style: none; padding-left: 0; margin: 0.5rem 0 0 0; }
        li.tool { background: #fff8e1; padding: 0.5rem; border-radius: 4px; margin-bottom: 0.25rem; font-size: 0.85rem; }
        .tool__status { color: #52606d; font-size: 0.75rem; }
        .error { color: #c0392b; font-weight: 600; }
        footer { margin-top: 2rem; font-size: 0.75rem; color: #52606d; text-align: center; }
        """;
}
