name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  repository-checks:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run base CI checks
        run: bash scripts/ci.sh

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v20
        with:
          globs: |
            **/*.md

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@4bf5b9076dc10522b81d12bcf78d00298067fbc8 # v4
        with:
          global-json-file: global.json

      - name: Restore, build and test Tau
        run: bash scripts/verify-dotnet.sh
