using System.Text.Json;
using System.Text.Json.Serialization;

namespace Tau.Ai.Serialization;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    Converters = [typeof(ModelJsonConverter)],
    WriteIndented = false)]
[JsonSerializable(typeof(ChatMessage))]
[JsonSerializable(typeof(UserMessage))]
[JsonSerializable(typeof(SystemMessage))]
[JsonSerializable(typeof(AssistantMessage))]
[JsonSerializable(typeof(DeferredHandle))]
[JsonSerializable(typeof(AssistantMessageDiagnostic))]
[JsonSerializable(typeof(DiagnosticErrorInfo))]
[JsonSerializable(typeof(ToolResultMessage))]
[JsonSerializable(typeof(NestedToolCalls))]
[JsonSerializable(typeof(ContentBlock))]
[JsonSerializable(typeof(TextContent))]
[JsonSerializable(typeof(ThinkingContent))]
[JsonSerializable(typeof(ImageContent))]
[JsonSerializable(typeof(ToolCallContent))]
[JsonSerializable(typeof(Tool))]
[JsonSerializable(typeof(Model))]
[JsonSerializable(typeof(ModelInputLimits))]
[JsonSerializable(typeof(ModelPromptCache))]
[JsonSerializable(typeof(StoredModel))]
[JsonSerializable(typeof(Registry.ModelsStoreEntry))]
[JsonSerializable(typeof(Dictionary<string, Registry.ModelsStoreEntry>))]
[JsonSerializable(typeof(List<object>))]
[JsonSerializable(typeof(object[]))]
[JsonSerializable(typeof(ImagesModel))]
[JsonSerializable(typeof(ClassifierModel))]
[JsonSerializable(typeof(ClassifierModel[]))]
[JsonSerializable(typeof(ClassifierContext))]
[JsonSerializable(typeof(ClassifierOptions))]
[JsonSerializable(typeof(ClassifierResult))]
[JsonSerializable(typeof(ClassifierQuestion))]
[JsonSerializable(typeof(ClassifierAnswer))]
[JsonSerializable(typeof(ModelCompatibility))]
[JsonSerializable(typeof(VercelGatewayRouting))]
[JsonSerializable(typeof(Usage))]
[JsonSerializable(typeof(UsageCost))]
[JsonSerializable(typeof(ModelCost))]
[JsonSerializable(typeof(ThinkingBudgets))]
[JsonSerializable(typeof(StreamOptions))]
[JsonSerializable(typeof(SimpleStreamOptions))]
[JsonSerializable(typeof(ImagesOptions))]
[JsonSerializable(typeof(AssistantImages))]
[JsonSerializable(typeof(ImagesContext))]
[JsonSerializable(typeof(IReadOnlyList<ChatMessage>))]
[JsonSerializable(typeof(IReadOnlyList<ContentBlock>))]
[JsonSerializable(typeof(IReadOnlyList<Tool>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(JsonElement))]
internal partial class TauAiJsonContext : JsonSerializerContext;
